import sys,os

gslpath = os.environ['CORAL_GSLPATH']
x11path = os.environ['CORAL_X11PATH']
coralhome = os.environ['CORAL_HOME']
ccflags = os.environ['CORAL_CCFLAGS']

os.system('scons -C '+coralhome)

env = Environment( \
  CPPPATH = [coralhome+'include', gslpath+'include'],\
	LIBPATH = [coralhome+'lib', gslpath+'lib'],\
	LIBS = ['coral','coralutils','gsl','gslcblas'],\
	CCFLAGS = ccflags, \
	LDFLAGS = '',\
	#ENV = \{'PATH':os.environ['PATH']\}\
)
env.Program('phasefit','phasefit.cc')
env.Program('coultest','coultest.cc')

xenv = Environment( \
  CPPPATH = [coralhome+'include', x11path+'include', gslpath+'include'],\
	LIBPATH = [coralhome+'lib', x11path+'lib', gslpath+'lib'],\
	LIBS = ['xgraph','coral','coralutils','gsl','gslcblas','X11'],\
	CCFLAGS = ccflags, \
	LDFLAGS = '',\
	#ENV = \{'PATH':os.environ['PATH']\}\
)
xenv.Program('plotphaseshifts','plotphaseshifts.cc')
