import sys,os

gslpath = os.environ['CORAL_GSLPATH']
x11path = os.environ['CORAL_X11PATH']
coralhome = os.environ['CORAL_HOME']
ccflags = os.environ['CORAL_CCFLAGS']

os.system('scons -C '+coralhome)

env = Environment( \
  CPPPATH = [coralhome+'include', gslpath+'include', x11path+'lib'],\
	LIBPATH = [coralhome+'lib', gslpath+'lib', x11path+'lib'],\
	LIBS = ['coral','coralutils','gsl','gslcblas','xgraph','X11'],\
	CCFLAGS = ccflags, \
	LDFLAGS = '',\
	#ENV = \{'PATH':os.environ['PATH']\}\
)
env.Program('sourcefit_3dgaussian','sourcefit_3dgaussian.cc')
env.Program('fakefit_3dgaussian','fakefit_3dgaussian.cc')
env.Program('sourcefit_blast','sourcefit_blast.cc')
env.Program('sourcefit_3dgaussian','sourcefit_3dgaussian.cc')
env.Program('graphsource','graphsource.cc')
