import sys,os

gslpath = os.environ['CORAL_GSLPATH']
x11path = os.environ['CORAL_X11PATH']
coralhome = os.environ['CORAL_HOME']
ccflags = os.environ['CORAL_CCFLAGS']

os.system('scons -C '+coralhome)

env = Environment( \
  CPPPATH = [coralhome+'include', gslpath+'include'],\
	LIBPATH = [coralhome+'lib', gslpath+'lib'],\
	LIBS = ['coral','coralutils','gsl','gslcblas'],\
	CCFLAGS = ccflags, \
	LDFLAGS = '',\
	#ENV = \{'PATH':os.environ['PATH']\}\
)


env.Program('ptgetter','ptgetter.cc')
env.Program('spectra','spectra.cc')