import sys,os

gslpath = os.environ['CORAL_GSLPATH']
x11path = os.environ['CORAL_X11PATH']
coralhome = os.environ['CORAL_HOME']
ccflags = os.environ['CORAL_CCFLAGS']

os.system('scons -C '+coralhome)

env = Environment( \
  CPPPATH = [coralhome+'include', gslpath+'include'],\
	LIBPATH = [coralhome+'lib', gslpath+'lib'],\
	LIBS = ['coral','coralutils','gsl','gslcblas'],\
	CCFLAGS = ccflags, \
	LDFLAGS = '',\
	#ENV = \{'PATH':os.environ['PATH']\}\
)

env.Program('cfmaker3d_oscar','cfmaker3d_oscar.cc')
env.Program('cfmaker3d_oscar_fullwf','cfmaker3d_oscar_fullwf.cc')
#env.Program('cfmaker_gauss','cfmaker_gauss.cc')
#env.Program('cfmakerCH_oscar','cfmakerCH_oscar.cc')
#env.Program('cftester','cftester.cc')
env.Program('sourcefit_3dgaussian','sourcefit_3dgaussian.cc')
env.Program('sourcefit_3dgaussian_bowlersinyukov','sourcefit_3dgaussian_bowlersinyukov.cc')
env.Program('sourcefit_3dgaussian_fullwf','sourcefit_3dgaussian_fullwf.cc')
#env.Program('sourcefit_gaussian','sourcefit_gaussian.cc')
#env.Program('chi2tester','chi2tester.cc')
env.Program('ptgetter','ptgetter.cc')
