import sys,os

gslpath = os.environ['CORAL_GSLPATH']
x11path = os.environ['CORAL_X11PATH']
coralhome = os.environ['CORAL_HOME']
ccflags = os.environ['CORAL_CCFLAGS']

os.system('scons -C '+coralhome)

env = Environment( \
  CPPPATH = [coralhome+'include', gslpath+'include'],\
	LIBPATH = [coralhome+'lib', gslpath+'lib'],\
	LIBS = ['coral','coralutils','gsl','gslcblas'],\
	CCFLAGS = ccflags, \
	LDFLAGS = '',\
	#ENV = \{'PATH':os.environ['PATH']\}\
)
env.Program('wfsample','wfsample.cc')
env.Program('kernelsample','kernelsample.cc')
env.Program('sourcesample_gauss','sourcesample_gauss.cc')
env.Program('sourcesample_OSCAR','sourcesample_OSCAR.cc')
env.Program('sourcesample_blast','sourcesample_blast.cc')
env.Program('source2CFsample','source2CFsample.cc')
env.Program('gausscheck','gausscheck.cc')